name: fmpm
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - altair
  - matplotlib
  - nosetests
  - numpy
  - pandas
  - pip
  - python
  - pytorch
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - torchvision
